### ISSUE TITLE
Styling of active route link

### ISSUE THREAD

**Issue by elderapo** [typehero/type-route#36]
Is it possible to style an active route link? I am using `styled-components` and it would be cool if it was possible to make `route.link()` return some additional prop to currently active link. Ex:

```ts
<MyLink {...routes.link()}>Some link</MyLink>;

...

const MyLink = styled.a<{ isActive?: boolean }>`
  color: ${props => (props.isActive ? "red" : "blue")};
`;
```

Injecting an active class would work too:

```ts
<MyLink {...routes.link()}>Some link</MyLink>

...

const MyLink = styled.a`
  color: blue;
  .active {
    color: red;
  }
`;
```

**Comment by bradenhs** [comment]
Unfortunately, implementing this would be fairly complicated since it would be necessary to make the link implicitly aware of the current application state. I'm not quite sure how this would be accomplished. Since Type Route is not directly connected with React there's not a great way for it to trigger a re-render when the url changes. In order to accomplish this Type Route would need a connection to React and would probably have to move to using a `Router` / `Link` component api. With the current api I accomplish the styling of the active link by passing down the current route to a `Navigation` component which then conditionally applies a class if the current route matches the link. Something like this:

```tsx
type Props = {
  route: Route<typeof routes>
}

function Navigation({ route }: Props) {
  return <nav>
    <a {...routes.home().link} className={route.name === "home" ? "active" : undefined}>Home</a>
    <a {...routes.other().link} className={route.name === "other" ? "active" : undefined}>Other</a>
  </nav>
}
```

**Comment by elderapo** [comment]
Yeah, this works, but you don't always want to prop drill. I worked around that by creating react context that contains the current route and allows to do something like:

```tsx
const isActive = useIsActive();

return <a {...routes.home.link()} className={isActive(routes.home) ? "active" : "not-active"}>Home</a>
```

The disadvantage of this is that `useIsActive` is not provided by `type-route` and that route kind of needs to be specified twice for a single link.

Perpahs it would make sense to create `@type-route/react` that would enable creating such helpers (passing current route via provider/context etc...) easier?

**Comment by bradenhs** [comment]
Its possible a package like that will exist at some point in the future. There a few too many unknowns at this stage for me to feel confident creating that. In the meantime I'd be curious which helpers you have created. That would definitely help inform any decision around what a future `type-route-react` library may look like.

**Comment by elderapo** [comment]
Right now just `useRouter` which basically wraps this logic:

```ts
const [route, setRoute] = React.useState(router.getCurrentRoute());
React.useEffect(() => router.listen(setRoute), []);
```

and `useCurrentRoute` for styling links that are currently active.

**Comment by bradenhs** [comment]
There's now a page in the docs for how to go about this: https://typehero.org/type-route/docs/guides/styling-active-route-link. I'm going to close this for now but am happy to continue discussion on how to improve the API to support use cases such as this.
